name: stay_near
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  firebase_core: ^4.14.0
  flutter:
    sdk: flutter
  flutter_map: ^8.3.2
  geocoding: ^5.0.0
  geolocator: ^14.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.2.3
  latlong2: ^0.10.1
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.17.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2
  fake_cloud_firestore: ^4.2.0
  firebase_auth_mocks: ^0.15.2

flutter:
  uses-material-design: true
