// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zj4Qt4ZRbH8uu0yxTR_km4kThum4FzY',
    appId: '1:1005233742071:web:1457fc33dce0dc911c73f2',
    messagingSenderId: '1005233742071',
    projectId: 'staynear-58ae7',
    authDomain: 'staynear-58ae7.firebaseapp.com',
    storageBucket: 'staynear-58ae7.firebasestorage.app',
    measurementId: 'G-KHEZ6JEF7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRLRg3JdamB5-tcxw0NAHOcsZ5nJnvts',
    appId: '1:1005233742071:android:3fdb4d41adad7e051c73f2',
    messagingSenderId: '1005233742071',
    projectId: 'staynear-58ae7',
    storageBucket: 'staynear-58ae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt9BxJ0aLy5CxaC9lElo1E0aG3gP77N6k',
    appId: '1:1005233742071:ios:446b961b532cf39f1c73f2',
    messagingSenderId: '1005233742071',
    projectId: 'staynear-58ae7',
    storageBucket: 'staynear-58ae7.firebasestorage.app',
    iosClientId: '1005233742071-kuga80581tfipnt0103q220fqf7jj6oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayNear',
  );
}
